---
spring:
  profiles: word-parser-fe
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://157.230.27.96:8010/eureka/
      
zuul:
  ignoredServices: '*'
  prefix: /parser-api
  routes:
    word-parser-gateway:
      url: http://157.230.27.96:8020
      path: /**
      serviceId: word-parser-gateway
  eureka:
    gateway:
      semaphore:
        maxSemaphores: 300
