# ---
# spring:
#   profiles: word-parser-fe

# eureka:
#   instance:
#     preferIpAddress: true
#   client:
#     register-with-eureka: true
#     serviceUrl:
#       defaultZone: http://157.230.27.96:8010/eureka/
      
# zuul:
#   ignoredServices: '*'
#   prefix: /parser-api
#   routes:
#     word-parser-gateway:
#       url: http://157.230.27.96:8020
#       path: /**
#       serviceId: word-parser-gateway
#   eureka:
#     gateway:
#       semaphore:
#         maxSemaphores: 300

---
spring:
  profiles: word-parser-fe

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    word-parser-gateway:
      url: http://localhost:8020
      path: /**
      serviceId: word-parser-gateway
  eureka:
    gateway:
      semaphore:
        maxSemaphores: 300
