# ---
# spring:
#   profiles: word-parser-gateway

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://157.230.27.96:8010/eureka/

# # zuul:
# #   prefix: /services
# zuul:
#   ignoredServices: '*'
#   routes:
#     word-parser-be:
#       path: /parser-api/**
#       serviceId: word-parser-be
#       stripPrefix: false

---
spring:
  profiles: word-parser-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

# zuul:
#   prefix: /services
zuul:
  ignoredServices: '*'
  routes:
    word-parser-be:
      path: /parser-api/**
      serviceId: word-parser-be
      stripPrefix: false
