---
spring:
  profiles: word-parser-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.75.1:8010/eureka/

# zuul:
#   prefix: /services
zuul:
  ignoredServices: '*'
  routes:
    word-parser:
      path: /parser-api/**
      serviceId: word-parser-service
      stripPrefix: false

