---
spring:
  profiles: word-parser-gateway
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://157.230.27.96:8010/eureka/

zuul:
  ignoredServices: '*'
  routes:
    word-parser-be:
       url: http://157.230.27.96:7001
       path: /parser-api/**
       serviceId: word-parser-be
       stripPrefix: false

# ---
# spring:
#   profiles: word-parser-gateway
#   servlet:
#     multipart:
#       max-file-size: 2MB
#       max-request-size: 2MB

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8010/eureka/

# # zuul:
# #   prefix: /services
# zuul:
#   ignoredServices: '*'
#   routes:
#     word-parser-be:
#       url: http://localhost:7001
#       path: /parser-api/**
#       serviceId: word-parser-be
#       stripPrefix: false
