---
spring:
  profiles: word-parser-fe

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
zuul:
  ignoredServices: '*'
  prefix: /parser-api
  routes:
    parser-api-proxy:
      url: http://localhost:8020
      path: /**
      serviceId: word-parser-gateway
  eureka:
    gateway:
      semaphore:
        maxSemaphores: 300
