---
spring:
  profiles: word-parser-gateway
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://157.230.27.96:8010/eureka/

# zuul:
#   prefix: /services
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ignoredServices: '*'
  routes:
    word-parser-be:
      path: /parser-api/**
      serviceId: word-parser-be
      stripPrefix: false
      
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
